site_name: FIO Wrapper 
repo_name: "fio_wrapper"
repo_url: "https://github.com/jplacht/fio_wrapper"

theme:
  name: "material"
  plugins:
    - optimize
    - typeset
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: light
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.sections
  - navigation.tabs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [fio_wrapper]
          options:
            show_source: true
            show_bases: true
            show_root_heading: false
            show_root_toc_entry: false
            heading_level: 3
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: table
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - search
  - coverage:
      page_name: coverage  # default
      html_report_dir: coverage  # default

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - FIO Wrapper: 
    - FIO Wrapper: index.md
    - Usage: usage.md
    - Available Routes: 'routes.md'  
    - Timeouts: 'timeouts.md'
  - Components:
    - FIO: fio.md
    - Adapter: fio_adapter.md
    - Decorators: decorator.md
    - Exceptions: exception.md
  - Endpoints (FIO 1.0): 
    - Building: 'endpoints/building.md'
    - Exchange: 'endpoints/exchange.md'
    - Group: 'endpoints/group.md'
    - LocalMarket: 'endpoints/localmarket.md'
    - Material: 'endpoints/material.md'
    - Planet: 'endpoints/planet.md'
    - Recipe: 'endpoints/recipe.md'
    - Sites: 'endpoints/sites.md'
    - Storage: 'endpoints/storage.md'
  - Models:
    - Building: 'models/building.md'
    - Exchange: 'models/exchange.md'
    - Group: 'models/group.md'
    - LocalMarket: 'models/localmarket.md'
    - Material: 'models/material.md'
    - Planet: 'models/planet.md'
    - Recipe: 'models/recipe.md'
    - Sites: 'models/sites.md'
    - Storage: 'models/storage.md'
  - Test Coverage:
    - Coverage Report: coverage.md